[build]
  base    = "frontend"  
  command = "npm run build"
  publish = ".next"

[[redirects]]
  from   = "/api/*"
  to     = "https://kaucja-boys.onrender.com/api/:splat"
  status = 200
  force  = true