[build]
  base    = "frontend"
  command = "npm run build"
  publish = "frontend/.next" # Or leave publish out so Netlify's Next.js plugin auto-detects it

[[redirects]]
  from   = "/api/*"
  to     = "https://kaucja-boys.onrender.com/api/:splat"
  status = 200
  force  = true
